project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Your Title (TBD)"
  author:
    - Khushi Advani (ka3090)
    - Ishmeen Garewal (ig2548)
  repo-url: https://github.com/ishmeen-11/EDAV-Project.git
  date: 11/17/2025
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


